### ISSUE TITLE
Error when running ng build -prod

### ISSUE THREAD

**Issue by awasum** [skylabaseInc/fineract-web-app#16]
![image](https://user-images.githubusercontent.com/15528032/36026331-d8248cc0-0d96-11e8-8b88-d8e78a8ac86d.png)

![image](https://user-images.githubusercontent.com/15528032/36026344-e3f73dae-0d96-11e8-92b8-398fc36c9e98.png)

**Comment by awasum** [comment]
am suing Nodejs version v8.9.4
and npm version: 5.6.0 on Ubuntu 16.04 LTS

**Comment by awasum** [comment]
When trying to build a production package which can be deployed on Nginx or Apache Web Server. I get the above error. Please look into this.

**Comment by kengneruphine** [comment]
i have fixed the date issues

**Comment by awasum** [comment]
@kengneruphine ....After you doing the fix, Did you run `ng build -prod` to make sure the app builds to production package successfully??

**Comment by awasum** [comment]
Because, I am getting the follow error after running the above command:

![image](https://user-images.githubusercontent.com/15528032/36059352-783ca864-0e37-11e8-8f53-3e8d67614168.png)

**Comment by awasum** [comment]
I am still getting this error:

![image](https://user-images.githubusercontent.com/15528032/36195476-e0033466-116d-11e8-8ef9-0283ac8a243d.png)


Please fix it.

**Comment by awasum** [comment]
Has this been fixed?
